<?php
	require_once("constant.php");
	require_once("util/Tool.php");
	require_once("util/DBHelp.php");
	require_once("util/Config.php");
	require_once("model/Content.php");
	require_once("model/Company.php");
	require_once("model/DocFile.php");
	require_once("model/Sort.php");
	require_once("model/Product.php");
	require_once("model/Message.php");
	require_once("model/User.php");
	require_once("model/Countor.php");
?>