<?php
	require_once("constant.php");
	require_once("class/Tool.class.php");
	require_once("class/DBHelp.php");
	require_once("util/DBHelp2.php");
	require_once("class/User.model.php");
	require_once("class/ProductQuery.model.php");
	require_once("model/Content.php");
	require_once("model/Company.php");
	require_once("model/DocFile.php");
	require_once("model/Sort.php");
	require_once("model/Product.php");
	require_once("model/Message.php");
?>